name: Java Maven Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Rename JAR file
      run: |
        echo "Renaming JAR file..."
        mv target/*.jar target/${{ secrets.JAR_NAME }}
      shell: bash
